#!/bin/bash
# DNS Checker .0001
# Will need to functionize it

ns=('1.1.1.1 8.8.8.8 9.9.9.9 4.2.2.2 208.67.220.220')
domain=$1
echo "DNS Checking against Cloudflare, Google, Quad9, Level 3, OpenDNS"
for i in $ns; do echo "Checking $domain against $i"; echo "" ; echo "Name Servers for $domain"; echo "---"; dig @$i NS $domain +short; echo "--";echo "A record for $domain"; echo "---"; dig @$i A $domain +short; echo "--"; echo "MX records for $domain"; echo "----"; dig @$i MX $domain +short; echo "---"; echo "TXT records for $domain"; dig @$i TXT $domain +short; echo " "; done

