#!/usr/bin/perl
# System Log and Cache
# Robert Taylor
# github.com/webpods/scripts/hl

START:

do_options();


if ($choice eq '0') {
	exit 0;
}

elsif ($choice eq '1') {
    print "\n\n-----\n";
    print "\nCompressing large log files in /var/log that are >100MB in size...\n";
    do_compress();
}

}

do_summary();
goto START;


sub do_options {
    # BEGIN CHOICE SELECTION
    print "\n";
    print "============================================================\n";
    print "System Log and Cache CLEANUP SCRIPT \n";
    print "============================================================\n\n";
    print "-> What do you want to do?

    [ 1 ] COMPRESS large /var/log/* (>100MB)
    [ 2 ] CLEAR package cache
    [ 3 ] VACUUM Journal Messages
    [ 0 ] Exit...

    Your choice (0 to 3): ";

    chomp ($choice=<STDIN>);
}

sub do_summary {
    $after_pct = `df -h /home | awk '{print \$5}' | sed '1d'`;
    $after_amount = `df -h /home | awk '{print \$4}' | sed '1d'`;

    chomp($after_pct, $after_amount);

    print "\n\n============================================================\n";
    print "\t /home has $after_pct free ($after_amount) after the clear!\n";
    print "============================================================\n\n";
}

sub do_compress {
    system('find /var/log -size +100M -exec gzip -9 -v  {} \\;
    print "\nDone.\n";
    print "\n-----\n\n";
}


#EFO
