#!/bin/bash
# Strips the seven digit number for ease of use (can be a complete URL)
# Example:
# ./kiss https://zion.webpods.com/test/1234567/t/d/-/1

tick=`grep -oP '(?<!\d)\d{7}(?!\d)' <<< $1`
echo "Logging $tick"
echo "---"

