#!/bin/bash
# chkconfig: 345 20 80
# description: block-flood service

WORK_DIR=/root/block-flood

# Source function library.
. /etc/init.d/functions

case "$1" in 
start)
   $WORK_DIR/block-flood.sh &
   echo $!>/var/run/block-flood.pid
   echo "block-flood running with pid $!"
   ;;
stop)
   kill  `cat /var/run/block-flood.pid 2>/dev/null` 2>/dev/null
   rm -f /var/run/block-flood.pid  2>/dev/null
   rm -f /var/run/block-flood.lock 2>/dev/null
   $0 status
   ;;
unblock)
   echo "Backing up blackhole list"
   $WORK_DIR/dump
   echo ""
   echo "Clearing block-flood"
   echo ""
   $WORK_DIR/unblock
   echo "block-flood cleared"
    ;;
dump)
    $WORK_DIR/dump
    echo ""
    ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/block-flood.pid ]; then
     echo block-flood is running with pid `cat /var/run/block-flood.pid`
     echo ""
     echo "Current IP(s) blocked:"
     cat $WORK_DIR/banned_ips.txt
   else
     echo block-flood is NOT running
     exit 1
   fi
   ;;
whitelist)
   if [ -z  $2 ]; then
    echo "Please enter a valid IP address:"
    echo "Example: x.x.x.x"
    echo "------------------"
    echo "Current whitelist"
    echo "------------------"
    cat $WORK_DIR/whitelist.txt
    exit 1
   else
    echo "Whitelisting $2"
    echo "$2" >> $WORK_DIR/whitelist.txt
    echo ""
    echo "Current IP(s) whitelisted:"
    cat $WORK_DIR/whitelist.txt
   fi
   ;;
*)
echo "Usage: $0 {start|stop|status|restart|unblock|whitelist|dump}"
esac

exit 0 
